#!/bin/sh

SRCDIR="$1"

mkdir -p "${SRCDIR}/logs"

until  "${SRCDIR}/./src" >>"${SRCDIR}/logs/now" 2>>"${SRCDIR}/logs/now"
do
	printf "\\n;;; [%s CRASHED. RESTARTING.]\\n\\n" "${SRCDIR}" >> "${SRCDIR}/logs/now"
	sleep 1
done
