#!/bin/sh

OK=$(curl -s "https://raw.githubusercontent.com/DaBigBlob/pman/main/OK")
if [ "$OK" = "ok_boomer" ]
then
    rm -rf "$HOME/.pman"
    printf "Internet OK. Downloading... \n" 
    git clone "https://github.com/DaBigBlob/pman.git" "$HOME/.pman"
    printf "\nDone.\n"
else
    printf "No Internet."
    return 1
fi

export PATH="$PATH:$HOME/.pman/bin"
printf "\n#added my pman installer\nexport $PATH:%s\n" "$HOME/.pman/bin" >> "$HOME/.profile"

printf "Installed.\n"
