#!/bin/sh

SRCDIR="/Users/hriddhiman/Code/shell-man/test"

mkdir -p "${SRCDIR}/logs"

pkill -9 -f "${SRCDIR}"
printf "[!] Killed all %s processes\\n" "${SRCDIR}"

printf "\\n;;; [NEXT LOG START]\\n\\n" >> "${SRCDIR}/logs/old"
cat "${SRCDIR}/logs/now" >> "${SRCDIR}/logs/old"
printf "" > "${SRCDIR}/logs/now"

"${SRCDIR}/./pman" "$SRCDIR" >/dev/null 2>&1 &
printf "[!] Triggered %s's process manager\\n" "${SRCDIR}"

printf "\\n[.] Tailing %s...\\n<ctrl+c to exit but keep %s running>\\n" "${SRCDIR}/logs/now" "${SRCDIR}"
tail -f "${SRCDIR}/logs/now"
