#!/bin/sh

SRCDIR="/home/hman/anon"
INTR="/home/hman/.homebrew/bin/node"

pkill -9 -f "${SRCDIR}"
printf "[!] killed all %s processes\\n" "${SRCDIR}"

mkdir -p "${SRCDIR}/logs"
printf "\\n;;; [NEXT LOG START]\\n\\n" >> "${SRCDIR}/logs/old"
cat "${SRCDIR}/logs/now" >> "${SRCDIR}/logs/old"
printf "" > "${SRCDIR}/logs/now"

"${SRCDIR}/./pman" "$SRCDIR" "$INTR" >/dev/null 2>&1 &
printf "[!] triggered %s's process manager\\n" "${SRCDIR}"

printf "[.] Done.\\n"
