#!/bin/sh

CMMD="sh test_src"
PNAME="test"

mkdir -p "$HOME/.pman/$PNAME"
LOGDIR="$HOME/.pman/$PNAME"

pkill -9 -f "${CMMD}"
pkill -9 -f "#this_will_be_killed_by_pman"
printf "\\033[34;1m[\\033[31;1m!\\033[34;1m]\\033[0m Killed all \\033[35;1m%s\\033[0m processes\\n" "${PNAME}"

printf "\\n;;; [STOPPED]\\n\\n" >> "${LOGDIR}/now.log"

printf "\\033[34;1m[\\033[32;1m*\\033[34;1m]\\033[0m Showing \\033[35;1m$%s\\033[0m...\\n" "${LOGDIR}/now.log"
less "${LOGDIR}/now.log"
printf "\\033[34;1m[\\033[32;1m*\\033[34;1m]\\033[0m Done.\\n"
