#!/bin/sh

red() {
    printf "\\033[34;1m[\\033[31;1m%s\\033[34;1m]\\033[0m %s\\033[35;1m%s\\033[0m%s\\n" "$1" "$2" "$3" "$4"
}
grn() {
    printf "\\033[34;1m[\\033[32;1m%s\\033[34;1m]\\033[0m %s\\033[35;1m%s\\033[0m%s\\n" "$1" "$2" "$3" "$4" 
}
gry() {
    printf "\\033[34;1m[\\033[30;1m%s\\033[34;1m]\\033[0m %s\\033[35;1m%s\\033[0m%s\\n" "$1" "$2" "$3" "$4" 
}

#arg check
if [ "$1" = "" ] || [ -z "$1" ]
then
    red "!!!" "Invalid arguments." "" "Exit."
    return 1
fi
SNAME="$1"

#db check
if [ ! -f "$HOME/.pman/ptable.db" ]
then
	red "!.." "" "$HOME/.pman/ptable.db" " missing. Creating..."
    mkdir -p "$HOME/.pman"
    printf "" > "$HOME/.pman/ptable.db"
fi

#get entries from db
PNAME=$(grep "$SNAME" "$HOME/.pman/ptable.db" | sed -e "s/.*;1;//" | sed -e "s/;2;.*//")

#log check
LOGDIR="$HOME/.pman/logs/$PNAME"
if [ ! -f "${LOGDIR}/now.log" ]
then
	red "..." "" "${LOGDIR}/now.log" " missing." ""
    mkdir -p "${LOGDIR}"
    gry "..." "Generating new log..."
    printf "" > "${LOGDIR}/now.log"
fi

grn "**." "Tailing " "${LOGDIR}/now.log" "..."
tail -F "${LOGDIR}/now.log"
